### ISSUE TITLE
Remove grouping by org/repo

### ISSUE THREAD

**Issue by warpech** [Starcounter/ReleaseJournal#1]
The list is grouped by Org name > Repo name, then sorted by Release date.

Is this useful? For me, it would be more practical to have it sorted just by the Release date descending.

@alshakero, @Mackiovello WDYT?

**Comment by alshakero** [comment]
I agree.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/ReleaseJournal/commit/5abf5ca1f16a8180d43239de9f9fe2ac031cc729

Please check the website on the repo's page.

**Comment by warpech** [comment]
As far as I can see, it is still grouped by org > repo, but sorted by last release date?

How do you decide what releases to show and what to not show?

I was thinking that we should not group by org/repo at all, just display a huge chronological list of all releases (maybe with pagination).

**Comment by alshakero** [comment]
It's currently:

- Repo (**repo-last-updated** December)
     - Release 2 - December
     - Release 1 - November _another release mentioned for context, doesn't affect sorting_
- Repo (last updated November)
     - Release 2 - November
     - Release 1 - July _another release mentioned for context, doesn't affect sorting_
- .
.
.

Each repo shows the latest <= 2 versions, **and repos are sorted by repo-last-updated**.

Do you think it should be just a list of latest single release from every repo?

**Comment by alshakero** [comment]
Hmm I think your version makes more sense, I'll go for it.

**Comment by warpech** [comment]
> Do you think it should be just a list of latest single release from every repo?

I think it should be **all** releases from all repos.

But maybe both versions are useful and there should be a checkbox "group by repo", which shows last 2 releases from that repo?

**Comment by alshakero** [comment]
Sounds good

**Comment by alshakero** [comment]
Do you like it now? https://releasenotes-mqxzlglbvu.now.sh

**Comment by warpech** [comment]
Not entirely, because it is still sorted by org/repo/release date.

It should be sorted only by release date.

**Comment by alshakero** [comment]
It was a tiny bug: https://releasenotes-vcdkinytml.now.sh

**Comment by warpech** [comment]
Yeah, that's what I was looking for :) Great job
