### ISSUE TITLE
Increase frequency of updates

### ISSUE THREAD

**Issue by warpech** [Starcounter/ReleaseJournal#2]
Is there a reason why it is updated every 12 hours? Can the interval be changed to every hour?

**Comment by alshakero** [comment]
Sure, I just thought there was no need. The update takes ~15 seconds because it's like 100 XHR requests (repoCount). And I didn't want to be selfish on free `now.sh`. Still, an hour is nothing.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/ReleaseJournal/commit/f814f7ba3becd8e878a940f2ed30b932c2b8acc3
